# Generated by Django 5.1.7 on 2025-04-03 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_mailing_end_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingattempt',
            name='mailing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt', to='mailing.mailing'),
        ),
    ]
