# Generated by Django 5.1.7 on 2025-04-05 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_alter_client_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': (('edit_client', 'Can edit client'),)},
        ),
    ]
