# Generated by Django 5.1.7 on 2025-04-05 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_alter_client_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
    ]
